trigger:
  branches:
    include:
    - refs/heads/part8
jobs:
- job: Job_2
  displayName: Test Coverage Job
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Test Coverage
    inputs:
      filePath: PipelineScripts/PremiumPerUser/LowCodeCoverage.ps1
    env:
      PPU_PASSWORD: $(PPU_PASSWORD) # Maps the secret variable